<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_city_container</name>
   <tag></tag>
   <elementGuidId>b2c3d4e5-f6a7-8901-bcde-f12345678901</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='city']</value>
      <webElementGuid>b2c3d4e5-f6a7-8901-bcde-f12345678902</webElementGuid>
   </webElementProperties>
</WebElementEntity>
