<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_state_container</name>
   <tag></tag>
   <elementGuidId>a1b2c3d4-e5f6-7890-abcd-ef1234567890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='state']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='state']</value>
      <webElementGuid>a1b2c3d4-e5f6-7890-abcd-ef1234567891</webElementGuid>
   </webElementProperties>
</WebElementEntity>
