<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a149aa2b-22b9-49eb-ae30-2a31da13ef65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='close-fixedban']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;adplus-dvertising&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#close-fixedban</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>31296856-6bf4-47ca-bc4f-9d1a739a64a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ad.plus/adplus-advertising.svg</value>
      <webElementGuid>e05e2fbb-01a8-49f0-a63d-80539967bf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>adplus-dvertising</value>
      <webElementGuid>a898a4b3-b5c3-4d25-a520-365fd124a6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ad.Plus Advertising</value>
      <webElementGuid>d833e2e1-1104-42a2-a1ab-9bf01b952831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-fixedban&quot;)/img[1]</value>
      <webElementGuid>ce768a0c-98bb-4d50-8b44-d5cb3216a17e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='close-fixedban']/img</value>
      <webElementGuid>7487ae6e-ac23-4269-ad41-bb3bf7da8cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='adplus-dvertising']</value>
      <webElementGuid>3d224bc5-ec37-4072-9d64-25a7ec3c0993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>846bec37-8a54-41c8-aeb8-28745c2b40d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ad.plus/adplus-advertising.svg' and @alt = 'adplus-dvertising' and @title = 'Ad.Plus Advertising']</value>
      <webElementGuid>7da5f0b8-6264-4d0b-9230-b830a83336b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
